language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 7.0

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
- echo "CREATE USER 'test'@'localhost' IDENTIFIED BY 'test';" | mysql -u root
- echo "GRANT ALL PRIVILEGES ON * . * TO 'test'@'localhost';" | mysql -u root
- echo "FLUSH PRIVILEGES;" | mysql -u root
- mysql -e 'create database ot_test;'
- mysql -e 'create database ot_dev;'
- composer install -o --prefer-dist

script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7' ]; then
      php tools/phpunit.phar
    else
      php tools/phpunit.phar --coverage-clover=coverage.clover
    fi

after_script:
  - |
      if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
          travis_retry wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover
      fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/62d2ef3db2dd2b321922
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

