language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly
    - php: 7.0
os:
  - linux
  - osx

cache:
  directories:
    - vendor

before_script:
- mysql -e 'create database ot_test;'
- composer self-update
- composer update
- php cli/config.php create
- php cli/migration.php migrations:migrate -n


script:
  - php tools/phpunit.phar --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
      if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
          travis_retry wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover
       fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/62d2ef3db2dd2b321922
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

