language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly
    - php: 7.0

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
- mysql -e 'create database ot_test;'
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install --prefer-dist
- php cli/config.php create
- php cli/migration.php migrations:migrate -n


script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7' ]; then
      php tools/phpunit.phar
    else
      php tools/phpunit.phar --coverage-text --coverage-clover=coverage.clover
    fi

after_script:
  - |
      if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
          travis_retry wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover
      fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/62d2ef3db2dd2b321922
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

