# Doctrine Migration File Generated on 2014-04-03 12:04:53

# Version Initial
CREATE TABLE users (id INT NOT NULL, username VARCHAR(254) NOT NULL, password VARCHAR(254) NOT NULL, logins INT UNSIGNED DEFAULT 0 NOT NULL, lastLogin DATETIME DEFAULT NULL, registered DATETIME DEFAULT NULL, lastAction DATETIME DEFAULT NULL, activationCode VARCHAR(255) DEFAULT NULL, email VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE roles (id INT NOT NULL, name VARCHAR(32) NOT NULL, description LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE user_roles (user_id INT NOT NULL, role_id INT NOT NULL, INDEX IDX_54FCD59FA76ED395 (user_id), INDEX IDX_54FCD59FD60322AC (role_id), PRIMARY KEY(user_id, role_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE maps (id INT NOT NULL, name VARCHAR(254) NOT NULL, width INT UNSIGNED NOT NULL, height INT UNSIGNED NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE tiles (id INT NOT NULL, name VARCHAR(254) NOT NULL, accessable TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE map_tiles (map_id INT NOT NULL, tile_id INT NOT NULL, x INT UNSIGNED NOT NULL, y INT UNSIGNED NOT NULL, INDEX IDX_9CE3CBD753C55F64 (map_id), INDEX IDX_9CE3CBD7638AF48B (tile_id), PRIMARY KEY(map_id, tile_id, x, y)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE cities (id INT NOT NULL, x INT UNSIGNED NOT NULL, y INT UNSIGNED NOT NULL, user_id INT NOT NULL, name VARCHAR(254) NOT NULL, INDEX IDX_D95DB16BA76ED395 (user_id), PRIMARY KEY(id, x, y)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE user_roles ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE user_roles ADD CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES roles (id);
ALTER TABLE map_tiles ADD CONSTRAINT fk_map FOREIGN KEY (map_id) REFERENCES maps (id);
ALTER TABLE map_tiles ADD CONSTRAINT fk_tile FOREIGN KEY (tile_id) REFERENCES tiles (id);
ALTER TABLE cities ADD CONSTRAINT fk_city_owner FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE SET NULL;
